version: '3'
services:
  api:
    container_name: flask_api
    build: .
    entrypoint: ["python", "app.py"]
    env_file:
      - .env
    
    ports:
      - '5000:5000'
  
  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes