services:
  redis_cache: #2nd container
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - api_vlan
    

  flask_api: #1st container 
    build: .   #building like docker build .
    image: flask_api #image_name
    ports:
      - 5000:5000
    networks:
      - api_vlan 
    depends_on:
      - redis_cache

#networks services here
networks:
  api_vlan:
    driver: bridge